### ISSUE TITLE
Docs CSS section overlap prevents some links from being easily clickable

### ISSUE THREAD

**Issue by mmolaro** [casadi/casadi.github.io#1]
You can see that subsequent section divs (at least in Chrome/Windows) overlap previous section this makes links that are near the end of a section difficult or impossible to click on. 

![casadidocs-issue](https://user-images.githubusercontent.com/9060669/42767964-21adc264-88d3-11e8-84b4-d302e06fe72c.png)

Chrome is reporting the div styling as 
```
#main.docs .content .section {
    margin-bottom: 1em;
    position: relative;
    display: block;
    clear: both;
    width: 100%;
}
```

The main culprit seems to be the `::before` psuedo-elements which when at the start of a new section are into the previous section.

**Comment by asteinh** [comment]
@mmolaro Thanks for reporting this! It should be fixed now (adding dummy anchors to each element having an id).
