### ISSUE TITLE
Docs claim fabs is "Modulus after division"

### ISSUE THREAD

**Issue by krisgry** [casadi/casadi.github.io#2]
https://github.com/casadi/casadi.github.io/blob/5e4b3d7b6c35839ad957ae2902183d141b18b688/content/docs/_index.html#L4726

Seems like a copy-paste error from the previous line

**Comment by edmundus** [comment]
Fix in #4

**Comment by jgillis** [comment]
For future refernce, the source is here: https://github.com/casadi/casadi/blob/develop/docs/users_guide/source/usage.rst
